"""empty message

Revision ID: 0ef05f39adc9
Revises: 8d6277c00759
Create Date: 2019-12-26 12:49:07.849202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef05f39adc9'
down_revision = '8d6277c00759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brandimage')
    op.add_column('brand', sa.Column('logo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand', 'logo')
    op.create_table('brandimage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name='brandimage_brand_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='brandimage_pkey')
    )
    # ### end Alembic commands ###
