"""empty message

Revision ID: 8d6277c00759
Revises: 90e70d3d704b
Create Date: 2019-12-07 20:19:47.947104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6277c00759'
down_revision = '90e70d3d704b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('auth_token_expire', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auth_token_expire')
    op.drop_column('user', 'auth_token')
    # ### end Alembic commands ###
